In [1]:
import numpy
print(numpy.__version__)

2.0.1


In [6]:
import numpy as np

## creat array using numpy
## creat 1D array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
## change 1dimension to 2d
arr2=np.array([1,2,3,4,5])
##arr2.reshape(1,5) in this we have one row and 5 column
arr2.reshape(5,1) ## in this part i have 5 row and 1 column

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
## 2d array
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape) ## it will show what dimension it is so it will show 2row and 5column

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [15]:
## arrange in numpy(starting,end but not included,diffrence)this is the formula for arange the array
np.arange(0,10,2).reshape(1,5)

array([[0, 2, 4, 6, 8]])

In [ ]:
## ones and zero there is some numpy you can get the matrices byeasily for your ml work
np.ones((3,4)) ## in this it will make unit number matrix of 3row and 4column

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
## identity matrices = identity matrix is matrix in which all the diagnol elements are 1
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
arr = np.array([[1,2,3],[4,5,6]])

print("array:\n", arr)
print("shape", arr.shape)
print("number of diension", arr.ndim)
print("size (number od elements):", arr.size)
print("data type:", arr.dtype)
print("item size(in bytes):", arr.itemsize)

array:
 [[1 2 3]
 [4 5 6]]
shape (2, 3)
number of diension 2
size (number od elements): 6
data type: int64
item size(in bytes): 8


In [21]:
## numpy vectorized operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

## Elemeants wise addition
print("addition:", arr1+arr2)

## Elements wise substraction
print("substraction:", arr1-arr2)

## Elements wise multiplication
print("multiplication:", arr1*arr2)

## Elements wise division
print("division:", arr1/arr2)

addition: [11 22 33 44 55]
substraction: [ -9 -18 -27 -36 -45]
multiplication: [ 10  40  90 160 250]
division: [0.1 0.1 0.1 0.1 0.1]


In [23]:
## univrsol function in array
arr=np.array([2,3,4,5,6])

##sqrroot
print(np.sqrt(arr))

##exponential
print(np.exp(arr))

##sin value
print(np.sin(arr))

##log vlaue
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [30]:
## array slicing and indexing
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("array:\n",arr)

array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [40]:
##print(arr[0][0])
print(arr[0:2, 2:]) ##3,4,7,8 here we are pick this element
print(arr[1:,1:3])


[[3 4]
 [7 8]]
[[ 6  7]
 [10 11]]


In [ ]:
arr[1:,2:] ## slicing 7,8,11,12 section

array([[ 7,  8],
       [11, 12]])

In [42]:
## modify array element
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [43]:
## statical concept--normalization
## to have a mean of 0 adn standard deviation of 1
data = np.array([1,2,3,4,5])

##calculate the mean and standard deviation
mean = np.mean(data)
std_dev=np.std(data)

## narmalize the data
normalized_data = (data-mean)/std_dev
print("Normalized data:", normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [44]:
## more statical operation
data = np.array([1,2,3,4,5,6,7,8,9,10])

## mean
mean_value=np.mean(data)
print("Mean:",mean_value)

## median
median_value=np.median(data)
print("Median:",median_value)

## standard deviation
std_dev=np.std(data)
print("Standard deviation:",std_dev)

## varience
varien=np.var(data)
print("variance:",varien)

Mean: 5.5
Median: 5.5
Standard deviation: 2.8722813232690143
variance: 8.25


In [46]:
## logical operation
data = np.array([1,2,3,4,5,6,7,8,9,10])
data[(data>=5) & (data<=8)]


array([5, 6, 7, 8])